routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DamageReportController;
use App\Http\Controllers\RepairShopController;
use App\Http\Controllers\CustomerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
#DamageReport Routes
Route::get('/', [DamageReportController::class, 'index'])->name('damageReport.index');
Route::post('damageReport.changeStatus/{damageReport}', [DamageReportController::class, 'changeStatus'])->name('damageReport.changeStatus');
Route::post('damageReport.changeStatusByShop/{damageReport}', [DamageReportController::class, 'changeStatusByShop'])->name('damageReport.changeStatusByShop');
Route::post('damageReport.reject/{damageReport}', [DamageReportController::class, 'reject'])->name('damageReport.reject');
Route::get('damageReport/{damageReport}', [DamageReportController::class, 'show'])->name('damageReport.show');

#RepairShop Routes
Route::resource('repairShops', RepairShopController::class);

#Customer Routes
Route::resource('customers', CustomerController::class);
Route::get('customersShow/{email?}', [CustomerController::class, 'show'])->name('customersShow');

app/Models/RepairShop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RepairShop extends Model
{
    use HasFactory;
    protected $table = 'repair_shops';
    protected $primaryKey = 'repair_shop_id';
    protected $fillable = [
        'repair_shop_email',
        'repair_shop_name',
        'repair_shop_latitude',
        'repair_shop_longitude',
        'repair_shop_status',
    ];

    public function damageReports()
    {
        return $this->belongsToMany(DamageReport::class, 'dr_has_rs','repair_shop_id','damage_report_id')->withPivot('is_shop_accepted');
    }
}

app/Http/Controllers/RepairShopController.php
<?php

namespace App\Http\Controllers;

use App\Models\RepairShop;
use Illuminate\Http\Request;

class RepairShopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $repairShop = RepairShop::all();
        return view('repairShop.index',compact('repairShop'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('repairShop.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'repair_shop_email' => 'required',
            'repair_shop_name' => 'required',
            'repair_shop_latitude' => 'required',
            'repair_shop_longitude' => 'required',
        ]);

        RepairShop::create($request->all());

        return redirect()->route('repairShops.index')
            ->with('success','RepairShop created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\RepairShop  $repairShop
     * @return \Illuminate\Http\Response
     */
    public function show(RepairShop $repairShop)
    {
        return view('repairShop.show',compact('repairShop'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\RepairShop  $repairShop
     * @return \Illuminate\Http\Response
     */
    public function edit(RepairShop $repairShop)
    {
        return view('repairShop.edit',compact('repairShop'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\RepairShop  $repairShop
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RepairShop $repairShop)
    {
        $request->validate([
            'repair_shop_email' => 'required',
            'repair_shop_name' => 'required',
            'repair_shop_latitude' => 'required',
            'repair_shop_longitude' => 'required',
        ]);

        $repairShop->update($request->all());

        return redirect()->route('repairShops.index')
            ->with('success','RepairShop updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\RepairShop  $repairShop
     * @return \Illuminate\Http\Response
     */
    public function destroy(RepairShop $repairShop)
    {
        try {
            $repairShop->delete();
            return redirect()->route('repairShops.index')
                ->with('success','RepairShop deleted successfully');
        } catch (\Exception $e) {
//            throw new \Exception($e->getMessage());
            return back()->with('error',"This repair shop allocated some jobs, Therefore you can't delete this shop");
        }
    }
}

resources/views/repairShop/create.blade.php
@extends('layout')

@section('content')
    <div class="max-w-4xl mx-auto mt-8">
        <div class="mb-4">
            <h1 class="text-3xl font-bold">
                Add New Repair Shop
            </h1>
            <div class="flex justify-end mt-5">
                <a class="px-2 py-1 rounded-md bg-sky-500 text-sky-100 hover:bg-sky-600" href="{{ route('repairShops.index') }}">< Back</a>
            </div>
        </div>

        <div class="flex flex-col mt-5">
            <div class="flex flex-col">
                <div class="inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg">
                    @if ($errors->any())
                        <div class="p-3 rounded bg-red-500 text-white m-3">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="w-full px-6 py-4 bg-white rounded shadow-md ring-1 ring-gray-900/10">
                        <form action="{{ route('repairShops.store') }}" method="POST">
                            @csrf
                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_name">
                                        Name
                                    </label>
                                    <input name="repair_shop_name" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_name" type="text" placeholder="Name">
                                </div>
                            </div>
                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_email">
                                        Email
                                    </label>
                                    <input name="repair_shop_email" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_email" type="text" placeholder="Email">
                                </div>
                            </div>
                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_latitude">
                                        Latitude
                                    </label>
                                    <input name="repair_shop_latitude" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_latitude" type="text" placeholder="Lat">
                                </div>
                                <div class="w-full md:w-1/2 px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_longitude">
                                        Longitude
                                    </label>
                                    <input name="repair_shop_longitude" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_longitude" type="text" placeholder="Lon">
                                </div>
                            </div>
                            <div class="flex items-center justify-start mt-4 gap-x-2">
                                <button type="submit" class="px-6 py-2 text-sm font-semibold rounded-md shadow-md text-green-100 bg-green-500 hover:bg-green-700 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/repairShop/edit.blade.php
@extends('layout')

@section('content')
    <div class="max-w-4xl mx-auto mt-8">
        <div class="mb-4">
            <h1 class="text-3xl font-bold">
                Edit Repair Shops
            </h1>
            <div class="flex justify-end mt-5">
                <a class="px-2 py-1 rounded-md bg-sky-500 text-sky-100 hover:bg-sky-600" href="{{ route('repairShops.index') }}">< Back</a>
            </div>
        </div>

        <div class="flex flex-col mt-5">
            <div class="flex flex-col">
                <div class="inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg">
                    @if ($errors->any())
                        <div class="p-5 rounded bg-red-500 text-white m-3">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="w-full px-6 py-4 bg-white rounded shadow-md ring-1 ring-gray-900/10">
                        <form action="{{ route('repairShops.update',$repairShop->repair_shop_id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_name">
                                        Name
                                    </label>
                                    <input name="repair_shop_name" value="{{$repairShop->repair_shop_name}}" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_name" type="text" placeholder="Name">
                                </div>
                            </div>
                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_email">
                                        Email
                                    </label>
                                    <input name="repair_shop_email" value="{{$repairShop->repair_shop_email}}" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_email" type="text" placeholder="Email">
                                </div>
                            </div>

                            <div class="flex flex-wrap -mx-3 mb-6">
                                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_latitude">
                                        Latitude
                                    </label>
                                    <input name="repair_shop_latitude" value="{{$repairShop->repair_shop_latitude}}" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_latitude" type="text" placeholder="Lat">
                                </div>
                                <div class="w-full md:w-1/2 px-3">
                                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="repair_shop_longitude">
                                        Longitude
                                    </label>
                                    <input name="repair_shop_longitude" value="{{$repairShop->repair_shop_longitude}}" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="repair_shop_longitude" type="text" placeholder="Lon">
                                </div>
                            </div>
                            <div class="flex items-center justify-start mt-4 gap-x-2">
                                <button type="submit" class="px-6 py-2 text-sm font-semibold rounded-md shadow-md text-green-100 bg-green-500 hover:bg-green-600 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/repairShop/index.blade.php
@extends('layout')

@section('content')
    <div class="container mx-auto px-4 sm:px-8">
        <div class="mb-4">
            <h1 class="text-3xl font-bold text-center">
                Repair Shops
            </h1>
        </div>

        <div class="flex justify-end mt-10">
            <a href="{{ route('repairShops.create') }}" class="px-2 py-1 rounded-md bg-blue-500 text-sky-100 hover:bg-blue-700">+ Create New Repair Shop</a>
        </div>

        <div class="flex flex-col mt-10">
            <div class="flex flex-col">
                <div class="inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg">
                    @if ($message = Session::get('success'))
                        <div class="p-3 rounded bg-green-500 text-green-100 mb-4 m-3">
                            <span>{{ $message }}</span>
                        </div>
                    @endif

                    @if ($message = Session::get('error'))
                        <div class="p-3 rounded m-3">
                            <strong>Whoops!</strong> There were some problems with this operation.<br><br>
                            <div class="p-3 rounded bg-red-500 text-green-100 mb-4 m-3">
                                <span>{{ $message }}</span>
                            </div>
                        </div>
                    @endif

                    <table class="min-w-full">
                        <tr>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50">No</th>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Name</th>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Email</th>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Lat | Lon</th>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Jobs</th>
                            <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase border-b border-gray-200 bg-gray-50" width="180px">Action</th>
                        </tr>
                        <tbody class="bg-white">
                        @foreach ($repairShop as $key =>$repairShop)
                            <tr>
                                <td class="px-6 whitespace-no-wrap border-b border-gray-200">{{ ++$key }}</td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">{{ $repairShop->repair_shop_name }}</td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">{{ $repairShop->repair_shop_email }}</td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">{{ $repairShop->repair_shop_latitude .' | '.$repairShop->repair_shop_longitude }}</td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                    <span class="relative inline-block px-3 py-1 font-semibold text-red-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-red-200 opacity-50 rounded-full"></span>
                                        <span class="relative">{{count($repairShop->damageReports)}}</span>
                                    </span>
                                </td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                    <form action="{{ route('repairShops.destroy',$repairShop->repair_shop_id) }}" method="POST">
                                        <a class="text-indigo-600 hover:text-indigo-900" href="{{ route('repairShops.show',$repairShop->repair_shop_id) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </a>

                                        <a href="{{ route('repairShops.edit',$repairShop->repair_shop_id) }}" class="text-indigo-600 hover:text-indigo-900 text-gray-600">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                            </svg>
                                        </a>

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-600 hover:text-red-800 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/repairShop/show.blade.php
@extends('layout')

@section('content')

    <div class="container mx-auto px-4 sm:px-8">
        <div class="mb-4">
            <h1 class="text-3xl font-bold">
                Show Repair Shop
            </h1>
            <div class="flex justify-end mt-5">
                <a class="px-2 py-1 rounded-md bg-sky-500 text-sky-100 hover:bg-sky-600" href="{{ route('repairShops.index') }}">< Back</a>
            </div>
        </div>
        <div class="flex flex-col mt-5">
            <div class="w-full px-6 py-4 bg-white rounded shadow-md ring-1 ring-gray-900/10">
                <h3 class="text-2xl font-semibold">Name: {{ $repairShop->repair_shop_name }}</h3>
                <p class="text-base text-gray-700 mt-5">Email: {{ $repairShop->repair_shop_email }}</p>
                <p class="text-base text-gray-700 mt-5">Latitude: {{ $repairShop->repair_shop_latitude }}</p>
                <p class="text-base text-gray-700 mt-5">Longitude: {{ $repairShop->repair_shop_longitude }}</p>
            </div>
        </div>

    </div>

    <div class="container mx-auto px-4 sm:px-8">
        <div class="py-8">
            <div>
                <h2 class="text-2xl font-semibold leading-tight">Damage Reports</h2>
            </div>
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow-md rounded-lg overflow-hidden">
                    <table class="min-w-full leading-normal">
                        <thead>
                        <tr>
                            <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                                Name
                            </th>
                            <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                                Email
                            </th>
                            <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                                description
                            </th>
                            <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                                Status
                            </th>
                            <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-700 uppercase tracking-wider">
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($repairShop->damageReports as $damageReport)
                            <tr>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-no-wrap">{{ $damageReport->customer_name }}</p>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-no-wrap">{{ $damageReport->customer_email }}</p>
                                </td>
                                <td class="w-[40%] px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-no-wrap">{{ $damageReport->description }}</p>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">

                                    @if($damageReport->pivot->is_shop_accepted === 1)
                                        <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                        <span class="relative">Accepted</span>
                                    </span>
                                    @elseif($damageReport->pivot->is_shop_accepted === 0)
                                        <span class="relative inline-block px-3 py-1 font-semibold text-red-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-red-200 opacity-50 rounded-full"></span>
                                        <span class="relative">Rejected</span>
                                    </span>
                                    @else
                                        <span class="relative inline-block px-3 py-1 font-semibold text-yellow-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-yellow-200 opacity-50 rounded-full"></span>
                                        <span class="relative">Pending</span>
                                    </span>
                                    @endif
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm text-center">

                                    <form method="POST" action="{{ url('damageReport.changeStatusByShop/'.$damageReport->damage_report_id) }}">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="repair_shop_id" value="{{$repairShop->repair_shop_id}}">
                                        <a class="py-3 px-4 inline-flex justify-center items-center rounded-md bg-blue-100 border border-transparent font-semibold text-blue-500 hover:text-white hover:bg-blue-100 focus:outline-none focus:ring-2 ring-offset-white focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" href="{{route('damageReport.show',$damageReport->damage_report_id)}}">Show</a>
                                        @if($damageReport->pivot->is_shop_accepted === NULL)
                                            <button type="submit" value="approve" name="action" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md bg-green-100 border border-transparent font-semibold text-green-500 hover:text-white hover:bg-green-100 focus:outline-none focus:ring-2 ring-offset-white focus:ring-green-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
                                                Accept
                                            </button>

                                            <button type="submit" value="reject" name="action" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md bg-red-100 border border-transparent font-semibold text-red-500 hover:text-white hover:bg-red-100 focus:outline-none focus:ring-2 ring-offset-white focus:ring-red-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800">
                                                Reject
                                            </button>
                                        @endif
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection